/* Technique catalogue.
 * kind: blast | barrage | beam | ball | disc | guided | instant | aoe | buff | special | rush
 * charge: ticks for a full charge (0 = fires on press).  cost: ki at full charge.
 * power: base damage at full charge.  learn: how to obtain it (shown in the menu).
 */
/** @type {Record<string, any>} */
export const TECHS = {
  ki_blast: { name: "気弾", kind: "blast", charge: 0, cost: 4, power: 7, color: "yellow", size: 0.6, speed: 1.9, radius: 1.2,
    pose: "one_hand", learn: { level: 1 }, desc: "基本の気弾。押すとすぐ撃てる。" },
  barrage: { name: "連続エネルギー弾", kind: "barrage", charge: 0, cost: 3, power: 4, color: "yellow", size: 0.5, speed: 2.1, radius: 1.0,
    pose: "beam_fire", learn: { level: 8 }, desc: "長押ししている間、気弾を連射する。" },
  rush: { name: "ラッシュ", kind: "rush", charge: 0, cost: 12, power: 4, pose: "rush", learn: { level: 12 },
    desc: "目の前の敵に一瞬で近づき、ものすごい速さで殴りまくる。" },
  explosive_wave: { name: "爆発波", kind: "aoe", charge: 20, cost: 35, power: 30, color: "white", radius: 7, pose: "transform",
    learn: { level: 20 }, desc: "自分の周り全体に気を放って吹き飛ばす。" },
  kamehameha: { name: "かめはめ波", kind: "beam", charge: 40, cost: 40, power: 42, color: "blue", width: 1.0, range: 34,
    pose: "beam_charge", firePose: "beam_fire", learn: { master: "roshi" }, desc: "亀仙流の奥義。両手に気を溜めて放つ。" },
  super_kamehameha: { name: "超かめはめ波", kind: "beam", charge: 60, cost: 75, power: 80, color: "blue", width: 1.8, range: 42,
    pose: "beam_charge", firePose: "beam_fire", learn: { master: "roshi", level: 35, needs: ["kamehameha"] }, desc: "限界まで溜めた特大のかめはめ波。" },
  kamehameha_x10: { name: "10倍かめはめ波", kind: "beam", charge: 50, cost: 110, power: 130, color: "blue", width: 2.4, range: 50,
    pose: "beam_charge", firePose: "beam_fire", learn: { master: "goku", level: 100, needs: ["kamehameha"] }, needForm: true,
    desc: "変身中にしか撃てない、10倍の威力のかめはめ波。" },
  galick_gun: { name: "ギャリック砲", kind: "beam", charge: 40, cost: 45, power: 46, color: "purple", width: 1.1, range: 34,
    pose: "beam_charge", firePose: "beam_fire", learn: { master: "vegeta" }, desc: "ベジータの必殺技。紫の気功波。" },
  final_flash: { name: "ファイナルフラッシュ", kind: "beam", charge: 70, cost: 100, power: 115, color: "yellow", width: 2.6, range: 52,
    pose: "beam_charge", firePose: "beam_fire", learn: { master: "vegeta", level: 50, needs: ["galick_gun"] }, desc: "全エネルギーを一点に集めて放つ大技。" },
  big_bang: { name: "ビッグバンアタック", kind: "ball", charge: 30, cost: 60, power: 85, color: "cyan", size: 2.2, speed: 1.6, radius: 6,
    pose: "one_hand", learn: { master: "vegeta", level: 60, needs: ["galick_gun"] }, desc: "片手から放つ巨大な気弾。大爆発を起こす。" },
  makankosappo: { name: "魔貫光殺砲", kind: "beam", charge: 80, cost: 60, power: 125, color: "yellow", width: 0.5, range: 50, spiral: true, pierce: true,
    pose: "forehead", firePose: "one_hand", learn: { master: "piccolo" }, desc: "額に指を当てて長く溜め、すべてを貫く螺旋の光線を放つ。" },
  masenko: { name: "魔閃光", kind: "beam", charge: 30, cost: 35, power: 38, color: "yellow", width: 1.0, range: 30,
    pose: "overhead", firePose: "beam_fire", learn: { master: "gohan" }, desc: "頭上で溜めた気を両手で撃ち出す。" },
  bakuretsu_mapa: { name: "爆裂魔波", kind: "beam", charge: 30, cost: 40, power: 48, color: "green", width: 3.0, range: 12,
    pose: "beam_charge", firePose: "beam_fire", learn: { master: "piccolo", level: 35, needs: ["makankosappo"] }, desc: "前方の広い範囲を爆発させる。" },
  kienzan: { name: "気円斬", kind: "disc", charge: 30, cost: 30, power: 70, color: "yellow", size: 1.4, speed: 1.3, homing: true, pierce: true,
    pose: "throw", learn: { master: "krillin" }, desc: "回転する気の円盤。敵を追いかけて切り裂く。" },
  taiyoken: { name: "太陽拳", kind: "instant", charge: 0, cost: 15, radius: 14, pose: "forehead", learn: { master: "tien" },
    desc: "まぶしい光で周りの敵の目をくらませ、動きを止める。" },
  dodonpa: { name: "どどん波", kind: "beam", charge: 10, cost: 15, power: 24, color: "yellow", width: 0.4, range: 32, pierce: true,
    pose: "one_hand", firePose: "one_hand", learn: { master: "tien" }, desc: "指先から撃つ細く速い光線。" },
  sokidan: { name: "繰気弾", kind: "guided", charge: 20, cost: 30, power: 34, color: "yellow", size: 0.9, speed: 1.2,
    pose: "one_hand", learn: { master: "yamcha" }, desc: "撃ったあと、見ている方向へ自由に操れる気弾。" },
  death_beam: { name: "デスビーム", kind: "beam", charge: 0, cost: 10, power: 26, color: "pink", width: 0.3, range: 36, pierce: true, instantBeam: true,
    pose: "one_hand", firePose: "one_hand", learn: { race: "frieza", level: 1, boss: "frieza4" }, desc: "指先から一瞬で放つ貫通光線。" },
  supernova: { name: "スーパーノヴァ", kind: "ball", charge: 80, cost: 120, power: 135, color: "orange", size: 4.5, speed: 0.7, radius: 10,
    pose: "overhead", learn: { race: "frieza", level: 40, boss: "frieza_golden" }, desc: "頭上に作った巨大な気の玉を投げつける。" },
  genkidama: { name: "元気玉", kind: "genki", charge: 200, cost: 50, power: 400, color: "cyan", size: 6, speed: 0.6, radius: 12,
    pose: "overhead", learn: { master: "kaio", level: 40 }, desc: "周りの生き物から元気を集める大技。集めるほど大きくなる。" },
  kaioken: { name: "界王拳", kind: "buff", charge: 0, cost: 10, pose: "transform", learn: { master: "kaio" },
    desc: "押すたびに 2倍→3倍→10倍→20倍→解除。強力だが体力が減っていく。" },
  instant_transmission: { name: "瞬間移動", kind: "special", charge: 0, cost: 30, pose: "forehead", learn: { master: "goku", level: 70 },
    desc: "気を感じた相手や登録した場所へ一瞬で移動する。" },
  chocolate_beam: { name: "お菓子になっちゃえ光線", kind: "beam", charge: 10, cost: 20, power: 25, color: "pink", width: 0.35, range: 24, candy: true,
    pose: "forehead", firePose: "forehead", learn: { race: "majin", level: 5 }, desc: "当たった普通の敵をお菓子に変える。ボスには普通のダメージ。" },
  power_ball: { name: "パワーボール", kind: "special", charge: 20, cost: 40, pose: "one_hand", learn: { master: "vegeta", level: 30, race: "saiyan" },
    desc: "空に人工の満月を作る。尻尾のあるサイヤ人が見ると大猿になる。" },
  regenerate: { name: "再生", kind: "instant", charge: 0, cost: 40, pose: "transform", learn: { race: ["namek", "majin"], level: 10 },
    desc: "体力を大きく回復する。" },
  heal: { name: "治療", kind: "instant", charge: 0, cost: 25, pose: "one_hand", learn: { race: "namek", level: 20 },
    desc: "目の前の仲間（いなければ自分）の体力を回復する。" },
  arm_stretch: { name: "腕伸ばし", kind: "instant", charge: 0, cost: 10, power: 16, pose: "one_hand", learn: { race: "namek", level: 5 },
    desc: "腕を伸ばして遠くの敵を殴り、引き寄せる。" },
  absorb: { name: "吸収", kind: "instant", charge: 0, cost: 30, pose: "fusion", learn: { race: "majin", level: 50 },
    desc: "弱った敵（体力3割以下）を吸収し、しばらく力を上乗せする。" },
};

export const TECH_ORDER = Object.keys(TECHS);
